### ISSUE TITLE
Cobblemon Incompatibility 

### ISSUE THREAD

**Issue by ghost** [magmamaintained/Magma-1.20.1#1]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.1 (Tried other version too besides this)

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/wcNVz

**Steps to Reproduce:**
 1. Have the Cobblemon Mod when trying to install

**Description of issue:** Whenever I try to install the server jar with the Cobblemon mod it crashes the server.

**Comment by TonimatasDEV** [comment]
Fixed. Restart the server for update to the latest. If you disabled the auto updater go to the releases page.
