### ISSUE TITLE
[1.20.1] Mixin error caused by unknown issue

### ISSUE THREAD

**Issue by Thspooks** [magmamaintained/Magma-1.20.1#10]
I've stubled upon another issue. Attaching crashlog. At first i thought it might be origins, mca or pehkui, but after deleting those problem persists. Including modlist too. I have no single clue what causes it 
Of course ill provide more info if i missed something
https://pastebin.com/MLfY0eKb
[cra.txt](https://github.com/magmamaintained/Magma-1.20.1/files/13653475/cra.txt)

**Comment by TonimatasDEV** [comment]
> I've stubled upon another issue. Attaching crashlog. At first i thought it might be origins, mca or pehkui, but after deleting those problem persists. Including modlist too. I have no single clue what causes it Of course ill provide more info if i missed something https://pastebin.com/MLfY0eKb [cra.txt](https://github.com/magmamaintained/Magma-1.20.1/files/13653475/cra.txt)

Delete client side mods, "Entity Culling", "BetterThirdPerson", "Controlling", "continuity", "DetailArmorBar", "ItemBorders", "ItemPhysicLite", "MouseTweaks", "oculus", "soundphysics"...

"Saturn", "FerriteCore" and "MemoryLeakFix" do the same, delete two. I recomend only use "FerriteCore"

**Comment by TonimatasDEV** [comment]
> I've stubled upon another issue. Attaching crashlog. At first i thought it might be origins, mca or pehkui, but after deleting those problem persists. Including modlist too. I have no single clue what causes it Of course ill provide more info if i missed something https://pastebin.com/MLfY0eKb [cra.txt](https://github.com/magmamaintained/Magma-1.20.1/files/13653475/cra.txt)

And send the latest log

**Comment by Thspooks** [comment]
Alr, will do in a bit. i should mention ive sent clientside modlist so ive delted all the clientside but ill make sure i didnt missed anything

**Comment by Thspooks** [comment]
[latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13665489/latest.log)
Here it is

**Comment by Thspooks** [comment]
Do you have any idea whats causing it? ill just delete the mod but i cant tell whats casuing it, idk what contains reach entity attributes, i only know its related to fabric, or it is connector related? 

EDIT: I think its Connector extras, because once i deleted it a error changed to better nether

**Comment by Thspooks** [comment]
Okay, it looks like magma is still incompatible with bc lib. 
[latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13687851/latest.log)

**Comment by TonimatasDEV** [comment]
@Thspooks The cause is Connector Extras, is difficult to fix but the fix is planned

**Comment by Thspooks** [comment]
That it is, the crash because of better nether was me not using the hotfix versions someone made on github. Basically BetterX mods and BClib were incompatible with any servers and crashed on startup with CLIENT_CONFIG as a reason. Good that  connector extras isnt required for BetterX mods. Otherwise everything works just perfectly! Thank you
