### ISSUE TITLE
AntiXray Mod Crash

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#15]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
MagmaMaintained version   1.20.1-58f3084
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** https://mclo.gs/oymFifU

**Steps to Reproduce:**
 1. Install AntiXray mod
 2. Launch the server

**Description of issue:**
Mixin issue

https://modrinth.com/mod/anti-xray

**Comment by TonimatasDEV** [comment]
**Fixed**
