### ISSUE TITLE
FAWE plugins not working

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#16]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
MagmaMaintained version   1.20.1-2777017
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** https://mclo.gs/YL7w3cZ

**Steps to Reproduce:**
 1. Install FastAsyncWorldEdit-Bukkit-2.8.2
 2. Join the server
 3. execute command //wand & //set & //replace etc..

**Description of issue:**
![image](https://github.com/magmamaintained/Magma-1.20.1/assets/130253873/eff7b36f-7081-40cb-8094-d1902d5c478e)

**Comment by TonimatasDEV** [comment]
> ## Running on Java 17.0.9 (Eclipse Adoptium)
> MagmaMaintained version 1.20.1-2777017
> Bukkit version v1_20_R1
> Forge version 47.2.17
> **Logs:** https://mclo.gs/YL7w3cZ
> 
> **Steps to Reproduce:**
> 
> 1. Install FastAsyncWorldEdit-Bukkit-2.8.2
> 2. Join the server
> 3. execute command //wand & //set & //replace etc..
> 
> **Description of issue:** ![image](https://private-user-images.githubusercontent.com/130253873/291022966-eff7b36f-7081-40cb-8094-d1902d5c478e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3Nzc0ODQsIm5iZiI6MTcwMjc3NzE4NCwicGF0aCI6Ii8xMzAyNTM4NzMvMjkxMDIyOTY2LWVmZjdiMzZmLTcwODEtNDBjYi04MDk0LWQxOTAyZDVjNDc4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwMTM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njc4OTM2YTgzZDc1NWNmOGJlMWVmNTU2YWVhYTM4MjBkZjkzZDY2OGM1ZWI5ZWM3ZWMwYmYxYzM4M2ExY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8lMsf5b4gyY2YrboWS5L_QyQx9llZT0nfC1lK80NQks)

Don't use fawe now. Use the normal WorldEdit
