### ISSUE TITLE
It won't install

### ISSUE THREAD

**Issue by ghost** [magmamaintained/Magma-1.20.1#2]
**Minecraft Version:** 1.20.1

**Forge Version:**47.1.1

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/iMbms

**Steps to Reproduce:**
 1. Try and install the File

**Description of issue:**
It won't install the file and crashes

**Comment by C0D3-M4513R** [comment]
Some hosting providers do wierd stuff to gson.
Otherwise just retry.

**Comment by Squidistry** [comment]
So I can't use this jar then?
