### ISSUE TITLE
Ambassador(proxy side) with luckperms(backend side) can't join the server

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#22]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version   1.20.1-adec9ce
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** https://mclo.gs/yRqdtjU
**Steps to Reproduce:**
 1. Install Ambassador latest version on velocity-3.2.0-SNAPSHOT
 2. Install PCF on Magma
 3. set online-mode to false in server.properties and type the velocity's forwarding.secret to config/pcf-common.toml
 4. Install luckperms-bukkit latest version on Magma
 5. Join the server
 
**Description of issue:**
https://github.com/adde0109/Ambassador
https://github.com/adde0109/Proxy-Compatible-Forge
https://luckperms.net/download

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
