### ISSUE TITLE
worldedit report

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#23]
**Minecraft Version:** 1.20.1

**Magma Version**Magma-1.20.1-0d40c54

**Forge Version:** forge-1.20.1-47.2.17

**Logs:** 
[latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13789107/latest.log)

WorldEdit v7.2.18+6616-abda4e0 and latest versión 1.20.2 problems 

**Steps to Reproduce:**
 1. install worldedit
 2. start server
 3. use plugins
 4.spam error in console and minecraft ctachat 

**Description of issue:**

**Comment by ssebaa** [comment]
in my case its wordguard that throws errors, however it may be on my end.
edit: nvm, mine world edit errors too
