### ISSUE TITLE
can't load the server, this error showed, removed libraries folder ten times by now

### ISSUE THREAD

**Issue by ssebaa** [magmamaintained/Magma-1.20.1#24]
Hey its me again!
After countless tries i decided to report this issue, sorry if this is on my end. Take a look:
```Magma version 1.20.1-1ef6acc
Loading libraries... 1% [> ] 2/122 (0:00:00 / 0:00:12) [1B
Loading libraries... 4% [=> ] 6/122 (0:00:00 / 0:00:05) [1B
Loading libraries... 9% [=> ] 11/122 (0:00:00 / 0:00:04) [1B
Loading libraries... 14% [===> ] 18/122 (0:00:00 / 0:00:02) [1B
Loading libraries... 18% [===> ] 22/122 (0:00:00 / 0:00:02) [1B
Loading libraries... 29% [======> ] 36/122 (0:00:00 / 0:00:02) [1B
Loading libraries... 33% [=======> ] 41/122 (0:00:01 / 0:00:01) [1B
Loading libraries... 36% [=======> ] 44/122 (0:00:01 / 0:00:01) [1B
Loading libraries... 36% [========> ] 45/122 (0:00:01 / 0:00:02) [1B
Loading libraries... 42% [=========> ] 52/122 (0:00:01 / 0:00:02) [1B
Loading libraries... 43% [=========> ] 53/122 (0:00:03 / 0:00:04) [1B
Loading libraries... 44% [=========> ] 54/122 (0:00:03 / 0:00:04) [1B
Loading libraries... 47% [==========> ] 58/122 (0:00:03 / 0:00:03) [1B
Loading libraries... 50% [===========> ] 62/122 (0:00:03 / 0:00:03) [1B
Loading libraries... 55% [============> ] 68/122 (0:00:03 / 0:00:03) [1B
Loading libraries... 59% [============> ] 72/122 (0:00:03 / 0:00:02) [1B
Loading libraries... 63% [==============> ] 78/122 (0:00:04 / 0:00:02) [1B
Loading libraries... 68% [===============> ] 84/122 (0:00:04 / 0:00:01) [1B
Loading libraries... 74% [================> ] 91/122 (0:00:04 / 0:00:01) [1B
Loading libraries... 79% [=================> ] 97/122 (0:00:04 / 0:00:01) [1B
Loading libraries... 88% [===================> ] 108/122 (0:00:04 / 0:00:00) [1B
Loading libraries... 100% [======================] 122/122 (0:00:04 / 0:00:00) [1B
Patching server... 0% [> ] 0/8 (0:00:00 / ?)
Patching server... 12% [===> ] 1/8 (0:00:00 / 0:00:04) [1B
Patching server... 25% [=======> ] 2/8 (0:00:00 / 0:00:02) [1B
Patching server... 37% [==========> ] 3/8 (0:00:00 / 0:00:01) [1B
Patching server... 50% [==============> ] 4/8 (0:00:01 / 0:00:01) [1B
Patching server... 62% [=================> ] 5/8 (0:00:03 / 0:00:01) [1B
Patching server... 75% [=====================> ] 6/8 (0:00:08 / 0:00:02) [1B
Patching server... 87% [========================> ] 7/8 (0:00:15 / 0:00:02) [1B
Patching server... 100% [============================] 8/8 (0:00:19 / 0:00:00) [1B
Exception in thread "main" java.lang.IllegalArgumentException: org.apache.commons.lang.enum: Invalid package name: 'enum' is not a Java identifier
```
I was trying to boot-up server from a crash but I can't boot it at all. Is this anyhow fixable my be or its a magma problem, again sorry if its's on my end. Have a nice day!

**Comment by TonimatasDEV** [comment]
> Hey its me again! After countless tries i decided to report this issue, sorry if this is on my end. Take a look:
> 
> ```
> Loading libraries... 1% [> ] 2/122 (0:00:00 / 0:00:12) �[1B
> Loading libraries... 4% [=> ] 6/122 (0:00:00 / 0:00:05) �[1B
> Loading libraries... 9% [=> ] 11/122 (0:00:00 / 0:00:04) �[1B
> Loading libraries... 14% [===> ] 18/122 (0:00:00 / 0:00:02) �[1B
> Loading libraries... 18% [===> ] 22/122 (0:00:00 / 0:00:02) �[1B
> Loading libraries... 29% [======> ] 36/122 (0:00:00 / 0:00:02) �[1B
> Loading libraries... 33% [=======> ] 41/122 (0:00:01 / 0:00:01) �[1B
> Loading libraries... 36% [=======> ] 44/122 (0:00:01 / 0:00:01) �[1B
> Loading libraries... 36% [========> ] 45/122 (0:00:01 / 0:00:02) �[1B
> Loading libraries... 42% [=========> ] 52/122 (0:00:01 / 0:00:02) �[1B
> Loading libraries... 43% [=========> ] 53/122 (0:00:03 / 0:00:04) �[1B
> Loading libraries... 44% [=========> ] 54/122 (0:00:03 / 0:00:04) �[1B
> Loading libraries... 47% [==========> ] 58/122 (0:00:03 / 0:00:03) �[1B
> Loading libraries... 50% [===========> ] 62/122 (0:00:03 / 0:00:03) �[1B
> Loading libraries... 55% [============> ] 68/122 (0:00:03 / 0:00:03) �[1B
> Loading libraries... 59% [============> ] 72/122 (0:00:03 / 0:00:02) �[1B
> Loading libraries... 63% [==============> ] 78/122 (0:00:04 / 0:00:02) �[1B
> Loading libraries... 68% [===============> ] 84/122 (0:00:04 / 0:00:01) �[1B
> Loading libraries... 74% [================> ] 91/122 (0:00:04 / 0:00:01) �[1B
> Loading libraries... 79% [=================> ] 97/122 (0:00:04 / 0:00:01) �[1B
> Loading libraries... 88% [===================> ] 108/122 (0:00:04 / 0:00:00) �[1B
> Loading libraries... 100% [======================] 122/122 (0:00:04 / 0:00:00) �[1B
> Patching server... 0% [> ] 0/8 (0:00:00 / ?)
> Patching server... 12% [===> ] 1/8 (0:00:00 / 0:00:04) �[1B
> Patching server... 25% [=======> ] 2/8 (0:00:00 / 0:00:02) �[1B
> Patching server... 37% [==========> ] 3/8 (0:00:00 / 0:00:01) �[1B
> Patching server... 50% [==============> ] 4/8 (0:00:01 / 0:00:01) �[1B
> Patching server... 62% [=================> ] 5/8 (0:00:03 / 0:00:01) �[1B
> Patching server... 75% [=====================> ] 6/8 (0:00:08 / 0:00:02) �[1B
> Patching server... 87% [========================> ] 7/8 (0:00:15 / 0:00:02) �[1B
> Patching server... 100% [============================] 8/8 (0:00:19 / 0:00:00) �[1B
> Exception in thread "main" java.lang.IllegalArgumentException: org.apache.commons.lang.enum: Invalid package name: 'enum' is not a Java identifier
> ```
> 
> I was trying to boot-up server from a crash but I can't boot it at all. Is this anyhow fixable my be or its a magma problem, again sorry if its's on my end. Have a nice day!

Delete libraries folder and test again

**Comment by TonimatasDEV** [comment]
@ssebaa Fixed, restart for update and try again.
