### ISSUE TITLE
Invalid package name: 'enum' is not a Java identifier

### ISSUE THREAD

**Issue by iPanic-Dev** [magmamaintained/Magma-1.20.1#25]
**Minecraft Version:** {Minecraft version}
1.20.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}
47.2.17

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://mclo.gs/JqvigDf

**Steps to Reproduce:**
 1. Download latest release, 1ef6acc
 2. Launch fresh server
 3. Error should display

**Description of issue:**
Trying the newest release it fails to boot after the patching stage. I've tried to delete the entire folder (libraries, logs, etc) a few times but it keeps coming back to this error.

**Comment by TonimatasDEV** [comment]
@iPanic-Dev Fixed, restart for update and try again.
