### ISSUE TITLE
FAWE doesn't recognize blocks

### ISSUE THREAD

**Issue by iPanic-Dev** [magmamaintained/Magma-1.20.1#26]
**Minecraft Version:** {Minecraft version}
1.20.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}
47.2.17

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
Initial error: https://mclo.gs/suuMSOE#L94

Block edit error: https://mclo.gs/suuMSOE#L253

**Steps to Reproduce:**
 1. Start server with FAWE, and release 4d577fd
 2. Try to do a worldedit such as `//set blue` 

**Description of issue:**
Currently unable to do any FAWE block edit commands. It looks like an error shows up around line 94 of the log mentioning that it's unable to pull the block list. Then it errors out on each command.

**Comment by TonimatasDEV** [comment]
Duplicated #28
