### ISSUE TITLE
Duplicate Entity ID

### ISSUE THREAD

**Issue by ghost** [magmamaintained/Magma-1.20.1#3]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.1

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/qBk7H

**Steps to Reproduce:**
 1.Take out 3+ pokemon
 2. Teleport using essentials or minecraft command to a random spot, can be loaded or unloaded
 3. It will crash saying in the console there is a duplicate entity

**Description of issue:**
This is a common issue with Cobblemon and hybrids, Cobblemon team said it was a hybrid related issue and something they'd had to fix. Whenever you teleport with a cobblemon out there is a chance it creates a duplicate entity and crashes the server. I've tested this several times and it's the same every time. It's a real hastle to deal with as everyone has their cobblemon out and it's difficult to keep this under control.

**Comment by TonimatasDEV** [comment]
> **Minecraft Version:** 1.20.1
> 
> **Forge Version:** 47.1.1
> 
> **Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} https://paste.ee/p/qBk7H
> 
> **Steps to Reproduce:** 1.Take out 3+ pokemon 2. Teleport using essentials or minecraft command to a random spot, can be loaded or unloaded 3. It will crash saying in the console there is a duplicate entity
> 
> **Description of issue:** This is a common issue with Cobblemon and hybrids, Cobblemon team said it was a hybrid related issue and something they'd had to fix. Whenever you teleport with a cobblemon out there is a chance it creates a duplicate entity and crashes the server. I've tested this several times and it's the same every time. It's a real hastle to deal with as everyone has their cobblemon out and it's difficult to keep this under control.

You are using Arclight, report this to https://github.com/IzzelAliz/Arclight/issues
