### ISSUE TITLE
Sign, Hanging Sign, Mod items Sign, etc.., sign gui does not open when place.

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#30]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version   1.20.1-a030357
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** No error logs

**Steps to Reproduce:**
 1. Place the any sign(can be mod items sign)
 2. sign gui does not open

**Description of issue:**
after mc version 1.20 if you place the any Sign block, then gui will open.
but magma does not. mod sign too(for example, [farmersdelight:gray_canvas_sign]).

**Comment by TonimatasDEV** [comment]
@sj-hub9796 It works now?
