### ISSUE TITLE
Worldguard & WorldguardExtraFlags keep-inventory, keep-exp flags not working

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#33]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version   1.20.1-f68ecc1
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** there's no any error logs

**Steps to Reproduce:**
 1. Install WorldGuard and WorldGuardExtraFlags
 2. Create Regions, and allow the keep-inventory, keep-exp flags.
 3. kill your self in that regions
 4. levels are gone and when you first die, the item appears to not be lost. but it's a fake item. so if you teleported or re-join the game then items are disappears.

**Description of issue:**
The items and levels doesn't even drops and just disappears.

**Comment by ssebaa** [comment]
I have the same issue with KeepInventory on my server without any regions

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
