### ISSUE TITLE
Hand swap not working again

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#37]
--------------------------------------
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version   1.20.1-a15e321
Bukkit version  v1_20_R1
Forge version   47.2.17
--------------------------------------

**Logs:** No error logs

**Steps to Reproduce:**
 1. Title says all

**Description of issue:**

**Comment by TonimatasDEV** [comment]
It works fine in vanilla magma
