### ISSUE TITLE
Crash ars nouveau.

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#39]
**Minecraft Version:** 1.20.1

**Forge Version:** forge-1.20.1-47.2.1

**Magma Version** 1.20.1-a15e321

**Logs:** [latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13835518/latest.log)

**Steps to Reproduce:**
 1. install mod 
 2. cut down a tree and let the sapling fall
 3. crash server

**Description of issue:**

**Comment by TonimatasDEV** [comment]
The WorldGuard/WorldEdit is duplicated #28

**Comment by TonimatasDEV** [comment]
Fixed
