### ISSUE TITLE
[Mod Issue] [6166f48] Crashing With GTCEU

### ISSUE THREAD

**Issue by hickorysb** [magmamaintained/Magma-1.20.1#40]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.17

**Logs:**
https://gist.github.com/hickorysb/08efd6941e755d1b88568836cc990caa  -- ATM 9 server
https://gist.github.com/hickorysb/2b195921a42b20cdeb201460e51385f4 -- Crash report from a server with only needed mods for GTCEU and Integrated Dynamics

**Steps to Reproduce:**
Install Integrated Dynamics 1.20.3 along with it's dependencies
Install GTCEU 1.0.17
Start Server
Experience Crash

**Description of issue:**
This issue started after my server performed an automatic update to 6166f48, it worked fine on 2a1c1da. Upon starting the server it very quickly crashes if GTCEU. GTCEU doesn't seem to even get far enough for a crash report without Integrated Dynamics. Integrated Dynamics does work on it's own.

**Comment by TonimatasDEV** [comment]
The latest Greg and Magma works fine.
