### ISSUE TITLE
Issues with Create's filters

### ISSUE THREAD

**Issue by Roshag** [magmamaintained/Magma-1.20.1#41]
Magma 1.20.1 6166f48
Well, I can't open filters with RMB. Works on Forge server, works in SP, works on another server. No errors in both client and server logs.
[latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13851359/latest.log)

**Comment by Snow-Custom** [comment]
same by me

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
