### ISSUE TITLE
VMP with sinytra not working

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#44]
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version 1.20.1-6166f48
Bukkit version v1_20_R1
Forge version 47.2.17

**Logs:** https://mclo.gs/YcSMbr9

**Steps to Reproduce:**
 1. Install VMP with sinytra, ffapi
 2. disable some options in vmp.properties

**Description of issue:**
server crashed. works fine on normal forge
vmp.properties: https://pastebin.com/HNfLmgfx

**Comment by TonimatasDEV** [comment]
Use the forge version
