### ISSUE TITLE
Wither No aparece al colocar su ritual

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#45]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.17

server difgiculty hard

**Steps to Reproduce:**
 1. ritual create
 2. Not Spawning
 

**Description of issue:**

**Comment by TonimatasDEV** [comment]
![2024-01-08_17 13 12](https://github.com/magmamaintained/Magma-1.20.1/assets/79017964/827c3edc-63fe-4d5e-9df1-968ddf9296e0)
