### ISSUE TITLE
Pickaxe with fortune 3 enchantment does not drop experience  when mine ores

### ISSUE THREAD

**Issue by sj-hub9796** [magmamaintained/Magma-1.20.1#49]
Running on Java 17.0.9 (Eclipse Adoptium)
Magma version 1.20.1-b18fa30
Bukkit version v1_20_R1
Forge version 47.2.17

**Logs:** there's no any error log

**Steps to Reproduce:**
 1. enchant your pickaxe with fortune
 2. mining any ores or etc that drops experience

**Description of issue:**
ores does not drop experience but if my pickaxe does not have fortune, ores are drop experience normally.

**Comment by Asaredapvp2** [comment]
This also happens on Forge 47.2.0

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
