### ISSUE TITLE
Some plugins aren't loading correctly / Working

### ISSUE THREAD

**Issue by ghost** [magmamaintained/Magma-1.20.1#5]
Hey I finally got it to install! But i notice a lot of plugins aren't working correctly
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.4
**Logs:**
Here are the latest logs and what the console says
https://paste.ee/p/3aAUw
https://paste.ee/p/eugjd

**Steps to Reproduce:**
 1. Install Magma Maintained
 2. Load it up and look at the tablist that previously worked with another jar
 3. plugins says Check server logs for error, and that it failed to load.

**Description of issue:**
A lot of plugins aren't working, like TAB, shopguiplus, randomtp, deluxemenus, autobroadcast, jobs, ecs, ibooks, ITF, playerkits, player points, tokenmanager, etc. 

Some plugins that do work are Luckperms, essentials, luckpermschat, crazyenvoys, discordsrv, limitcrafting, mycommand
These all previously worked on arclight, so I didn't set them up incorrectly.

All of these plugin versions are correct as well, as I've checked. They've also worked on arclight. 
I'll update these lists more once I find more that don't work, and more that do.

Here is also a crash report I get occasionally:
https://paste.ee/p/neiqe

**Comment by ghost** [comment]
New Logs for after update
Console startup: https://paste.ee/p/T7nWN
Latest Logs: https://paste.ee/p/yBUJB

**Comment by ghost** [comment]
New logs for the plugin fix update:
https://paste.ee/p/WGzam

**Comment by ghost** [comment]
Now just a world loading issue, all plugins seem to work!
Chunks that I render seem to reset back to their original state. I do use multiverse, could that be an issue?
Logs: https://paste.ee/p/x8L0B

**Comment by TonimatasDEV** [comment]
> Now just a world loading issue, all plugins seem to work! Chunks that I render seem to reset back to their original state. I do use multiverse, could that be an issue? Logs: https://paste.ee/p/x8L0B

What mods are you using?

**Comment by ghost** [comment]
> > Now just a world loading issue, all plugins seem to work! Chunks that I render seem to reset back to their original state. I do use multiverse, could that be an issue? Logs: https://paste.ee/p/x8L0B
> 
> What mods are you using?

Here is my mods list https://paste.ee/p/dHr4m
Sorry, just now saw your reply

**Comment by ghost** [comment]
Logs for multiworld not working
https://paste.ee/p/1vLZ8

**Comment by Zenkono** [comment]
I don't know if its just something I did or what but I have a plugin called the tardis plugin and I can't seem to update it to its latest version because it needs Spigot/Paper 1.20.3 or higher anyway to fix this I assume magma runs v1_20_R1?

**Comment by TonimatasDEV** [comment]
> I don't know if its just something I did or what but I have a plugin called the tardis plugin and I can't seem to update it to its latest version because it needs Spigot/Paper 1.20.3 or higher anyway to fix this I assume magma runs v1_20_R1?

Yes, Magma runs v1_20_R1

**Comment by TonimatasDEV** [comment]
@Squidistry For me works fine in the latest version
