### ISSUE TITLE
essentialsx error no funcionan algunos comandos

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#50]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.17

**Logs:** 
[latest.log](https://github.com/magmamaintained/Magma-1.20.1/files/13928612/latest.log)

**Steps to Reproduce:**
 1. run server
 2.  join server
 3. spam error
 4. fly essentialsx not work and mods item fly not work  

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
