### ISSUE TITLE
Create mod item Filter did not work

### ISSUE THREAD

**Issue by Snow-Custom** [magmamaintained/Magma-1.20.1#54]
**Minecraft Version:** Magma 1.20.1

**Forge Version:** 47.2.0

**Logs:** no errors showing up

**Steps to Reproduce:**
 1. Download Create mod
 2. give your self a Item Filter
 3. Open the item filter on the last Magma Maintained version

**Description of issue:**

Create mod item Filter did not work the GUI ist instandly Closing i cant use the item anymore can you please fix it

**Comment by TonimatasDEV** [comment]
Duplicated #41
