### ISSUE TITLE
cañon de esuquemas de create no detecta ciertos bloques (en un jugador funciona)

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#55]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.20

**Logs:** 
[latest (1).log](https://github.com/magmamaintained/Magma-1.20.1/files/14016212/latest.1.log)

**Steps to Reproduce:**
 1. use schematic cañon 
 2. not work correctly
 3. ...

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
