### ISSUE TITLE
crash animal feeders crash therl series mod

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#57]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.20

**Logs 1:** 
[crash-2024-01-25_20.15.08-server.txt](https://github.com/magmamaintained/Magma-1.20.1/files/14073762/crash-2024-01-25_20.15.08-server.txt)
**Logs: 2:**
[crash-2024-01-26_19.57.15-server.txt](https://github.com/magmamaintained/Magma-1.20.1/files/14073769/crash-2024-01-26_19.57.15-server.txt)

**Logs 3:** 
[crash-2024-01-26_20.30.26-server.txt](https://github.com/magmamaintained/Magma-1.20.1/files/14073766/crash-2024-01-26_20.30.26-server.txt)

**Steps to Reproduce:**
 1. use animal feeder and feeding trough
 2. feeding animal
 3. crash server

1.use energy cell thermal mod
2.crash server

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
