### ISSUE TITLE
Empty tag forge

### ISSUE THREAD

**Issue by Craxell** [magmamaintained/Magma-1.20.1#6]
Fix a problem with some "Empty tag forge" crafts, but it works in singleplayer mode

![1](https://github.com/magmamaintained/Magma-1.20.1/assets/83180117/740d190a-75dc-4fe1-a8cd-29b3b3f3194d)
![2](https://github.com/magmamaintained/Magma-1.20.1/assets/83180117/57ceaa35-568f-440f-bbe7-02b5feba90a2)

**Comment by TonimatasDEV** [comment]
Fixed
