### ISSUE TITLE
Enchanting doesn't partially work

### ISSUE THREAD

**Issue by Asaredapvp2** [magmamaintained/Magma-1.20.1#60]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.0

**Logs:** [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket@66d6639e, suppressing error

**Steps to Reproduce:**
 1. Build Full 30 level enchant
 2. Then simply put an item + lapis to enchant
 3. Here you have enchant not accepting bookshelves + max enchant doesn't work

**Description of issue:**
Just how the title says, the enchanting doesn't work correctly.
Firstly, max enchant doesn't work and secondly the bookshelves are not recognised.

**Comment by TonimatasDEV** [comment]
Same error #48
