### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.20.1#64]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.20

**Logs:** 
[latest (8).log](https://github.com/magmamaintained/Magma-1.20.1/files/14395066/latest.8.log)

Modpack:https://www.mediafire.com/file/nsi47n84blokg2g/The-Lost-Cockroach-and-the-Human-Camera.rar/file

**Steps to Reproduce:**
 1. start server
 2. erro hugh entity error and worldguars spam console
 3. ...lag server an crash in 47m  

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Use [Ketting](https://github.com/kettingpowered/Ketting-1-20-x) 1.20.1
