### ISSUE TITLE
amethyst core

### ISSUE THREAD

**Issue by KrysisUchiha** [magmamaintained/Magma-1.20.1#7]
Error type: Mixin related error
Caused by: amethyst_core.mixins.json:PlayerEntityMixin
Short stack trace(s):
Critical injection failure: Callback method amethyst_core_applyMultiplicationAttributeToDamage(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/damagesource/DamageSource;FLcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)F in amethyst_core.mixins.json:PlayerEntityMixin from mod amethyst_core failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap amethyst_core-refmap.json
MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
TRANSFORMER/MixinExtras@0.3.1/com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.latePostInject(WrapOperationInjectionInfo.java:76)
TRANSFORMER/MixinExtras@0.3.1/com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationApplicatorExtension.postApply(WrapOperationApplicatorExtension.java:39)

Forge:1.20.1

**Comment by TonimatasDEV** [comment]
**Fixed:** https://github.com/magmamaintained/Magma-1.20.1/releases/tag/fdb013a
