### ISSUE TITLE
MySQL Driver

### ISSUE THREAD

**Issue by nixacik** [magmamaintained/Magma-1.20.1#8]
**Minecraft Version:** v1_20_R1
**Forge Version:** 47.2.16

**Logs:** 
Console: 
![image](https://github.com/magmamaintained/Magma-1.20.1/assets/55744915/f4b5329c-06eb-4b65-a96c-c4f0a930e4c7)
****
latest.txt: https://upload.nixacik.eu/W1152ra33c3uNJ8.log

**Steps to Reproduce:**
 1. Install Magma 1.20.1
 2. Start/Load server
 3. Console say error with mysql driver

**Description of issue:**
I started Magma in a completely empty folder, and after installing and starting the server with Magma, console say error with the MySQL driver for plugins. In these plugins, I use a MySQL database for retrieval and storage data. It will write errors for all plugins where I have MySQL enabled in the config.yml on "true".

I also tried to install paper 1.20.1 to install the libraries, but it didn't help.
When I switched the server version to classic paper 1.20.1, the plugins worked correctly.

Can you help me in any way or can you think of something? 
Well thank you.

**Comment by TonimatasDEV** [comment]
**Fixed**
