### ISSUE TITLE
[1.20.1] Critical injection failure: Argument modifier method crash on server startup

### ISSUE THREAD

**Issue by Thspooks** [magmamaintained/Magma-1.20.1#9]
I have a server and wanted to use magma with sinytra connector, but its crashing and it seems blaming betterend

1.20.1

Magma d8d319e

https://pastebin.com/kpUcctXg crashlog

https://pastebin.com/MLfY0eKb modlist (clienside so all clientside mods are removed on server itself, bc idk how to list mods on serverside)

**Comment by TonimatasDEV** [comment]
**Fixed**

**Comment by Thspooks** [comment]
Amazing, thank you, i saw some more incompabilities i think, but ill gather it into one post later!
